## 异常

- 对于除以零这种运算，许多编译器通过生成一个表示无穷大的特殊浮点值来处理，`cout`将这种值显示为`INF`。

- 调用`abort()`
  - 原型位于`cstdlib`头文件中
  - 向标准错误流发送“程序异常终止”的消息并终止程序。

- 返回错误码

### 异常机制

- 处理异常的组成部分：引发异常，使用处理程序捕获异常，使用`try`块

```cpp
void testExp()
{
    if () // 不被允许的操作
    {
        throw "this operation is not allowed";
    }
}

int main()
{
    try{
        testExp(); // 程序执行需要进行的操作
    }
    catch (const char* s){
        // 引发异常之后的操作
    }
}

```

- 引发异常
  - 上述`testExp`中被引发的异常是字符串类型，异常类型也可以是其他的C++类型，通常是类类型。
  - `throw`语句类似于执行`return`语句，将终止函数的执行，但`throw`不是将控制权返回给调用程序，而是沿函数调用序列后退，直到找到包含`try`块的函数（可以出现多步后退）。

- 如果函数引发了异常，而没有`try`块或与之对应（指与抛出的异常类型相对应的捕获异常）的处理程序时，在默认情况（可以修改）下，程序最终将调用`abort()`函数。

### 将对象用作异常类型

- 可以使用不同的异常类型来区分不同的函数在不同情况下引发的异常。
- 对象可以携带信息，可以根据这些信息确定引发异常的原因。